### ISSUE TITLE
perhaps shouldn't take over super+alt+n

### ISSUE THREAD

**Issue by jjb** [SublimeText/RSpec#28]
I noticed this after installing AdvancedNewfile (https://github.com/skuroda/Sublime-AdvancedNewFile), which wants super+alt+n for its new file command. rspec takes it over first, so it's not available.

perhaps super+alt+n is too generic for creating a new rspec file, and more appropriate for general utilities like AdvancedNewfile to use.

**Comment by princemaple** [comment]
Removed in `2.0.1`
