### ISSUE TITLE
Syntax highlight build output

### ISSUE THREAD

**Issue by princemaple** [SublimeText/RSpec#47]
Does anyone have experience about this?

**Comment by maksimf** [comment]
RubyTest is made as a plugin, whereas RSpec is made as build system, maybe that is the issue why we don't see colored output?

**Comment by maksimf** [comment]
Why you decide to close this? I'm currently researching about this issue btw...

**Comment by princemaple** [comment]
@maksimf good to know. A while ago, I read about how to do this and tested some stuff around, ended up with little success. I saw a notification about this thread, but didn't see a new comment, which probably deleted, thought it's weird :) lets reopen, and would be great if find out how to do it properly.

**Comment by maksimf** [comment]
By now I found out that there is actually syntax option available for build system: [here (at the bottom)](http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/reference/build_systems/exec.html)
So I tried to use [provided by RubyTest syntax file](https://github.com/maltize/sublime-text-2-ruby-tests/blob/master/TestConsole.tmLanguage) for RSpec output, but I'm currently stuck with colorizing output, I suppose we can somehow use [RubyTest's RSpec output theme](https://github.com/maltize/sublime-text-2-ruby-tests/blob/master/TestConsole.hidden-tmTheme). But I don't now how for now, any ideas?

**Comment by princemaple** [comment]
You can probably add something like
```xml
<key>settings</key>
<dict>
  <key>foreground</key>
  <string>#00FF00</string>
</dict>
```
after every definition
Not sure.. I suspect that the two fails serve different purposes. Worth trying anyway.
I got about this far, too, when I tried. I stopped there because it was getting tedious.

**Comment by maksimf** [comment]
I looked through the above files and it looks like they define only Cucumber syntax, so I don't understand where exactly they define 'styles' for RSpec and Minitest. Do you know?

**Comment by princemaple** [comment]
I don't. I would think Cucumber covers the RSpec part?

**Comment by maksimf** [comment]
Maybe, I'll try to ask about this [at superuser](https://superuser.com/questions/897494/sublime-text-colorize-build-system-output)

**Comment by princemaple** [comment]
Thanks a lot for the effort!

**Comment by maksimf** [comment]
I also [opened](http://www.sublimetext.com/forum/viewtopic.php?f=2&t=17918) topic at sublimetext forum, no answers yet, though.

**Comment by princemaple** [comment]
Thanks!

**Comment by maksimf** [comment]
@princemaple hope something helps, rly want to get it done :)

**Comment by princemaple** [comment]
It will be a great improvement if it gets done.

**Comment by bperucchi** [comment]
The output color has already been implemented?

**Comment by princemaple** [comment]
@bperucchi nope :cry:

**Comment by kmacdough** [comment]
@princemaple Two things here. In terms of syntax highlighting, check out https://github.com/aziz/SublimeANSI. Doesn't highlight mid-build in my experience but works in the end. Also, in the mean time can we please get the `--no-color` option? Feels kinda silly to render ANSI colors codes while they aren't working.
