### ISSUE TITLE
Shortcut opening wrong file

### ISSUE THREAD

**Issue by victoryftw** [SublimeText/RSpec#51]
I'm encountering an issue where using the ctrl/command + . shortcut doesn't open the correct file. Specifically, I have the following files:

lib/c/process.rb
lib/c/process_spec.rb
lib/u/process.rb
lib/u/process_spec.rb

The command works fine for switching back and forth between c/process.rb and c/process_spec.rb, but when I attempt to switch from u/process.rb to u/process_spec.rb, the command opens c/process_spec.rb instead. The same is true in reverse; u/process_spec.rb opens c/process.rb.

I can recreate this issue with several different sets of files in my codebase, and it appears to take the file that is in the parent directory (or maybe the module) which is alphabetically first. 

This bug is particularly bothersome because its not always immediately obvious which file was opened, since the files have the same name. Let me know if more information would be helpful in recreating the issue.

**Comment by jtippett** [comment]
I also encountered this issue on an app with an "interesting" file structure; my hack to fix it lives here: https://github.com/jtippett/RSpec/commit/8bf2a025afed3d0ebdb1c7d7becf82eb80ddaf23

The changes necessary to adapt to your own situation should be pretty obvious.
