### ISSUE TITLE
Can't find Gemfile when running with "bundle exec"

### ISSUE THREAD

**Issue by dustinhansen** [SublimeText/RSpec#58]
I'd love to use the "bundle exec" build system, but it seems like I can't locate the Gemfile unless the Gemfile is in the same directory as the test file? Here's my app layout:

/Gemfile
/splittest.rb
/spec/splittest.rb

When I run the build command on splittest.rb I get the **Could not locate Gemfile or .bundle/ directory** error. Any advice on this?

**Comment by princemaple** [comment]
Hi, let me tweak it a little bit so it works on project root.

**Comment by princemaple** [comment]
Actually it already works this way https://github.com/SublimeText/RSpec/blob/master/RSpec%20-%20Bundle%20Exec.sublime-build

**Comment by princemaple** [comment]
@dustinhansen if you start using the project system that sublime text provides, it should be able to pick up the project root.

**Comment by dustinhansen** [comment]
Thanks! I should have thought of that.
